//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitHead.SweetHome.Shared.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imoveis
    {
        public System.Guid Id { get; set; }
        public string Nome { get; set; }
        public string Link { get; set; }
        public string Regiao { get; set; }
        public string Observacoes { get; set; }
    }
}
